# Generated by Django 3.0.8 on 2020-09-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product_id',
            new_name='work_id',
        ),
    ]
