# Generated by Django 3.0.8 on 2020-09-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('catalog_type', models.CharField(max_length=30)),
                ('power', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('made', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('guarantee', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_0', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
