# Generated by Django 3.0.8 on 2020-09-19 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('product_type', models.CharField(blank=True, max_length=250)),
                ('voltage', models.IntegerField()),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_0', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
