# Generated by Django 3.0.8 on 2020-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
